#if !canImport(ObjectiveC)
import XCTest

extension SupportTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SupportTests = [
        ("testIntFromAscii", testIntFromAscii),
        ("testLogging", testLogging),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SupportTests.__allTests__SupportTests),
    ]
}
#endif
