#if !canImport(ObjectiveC)
import XCTest

extension SKLocalSwiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SKLocalSwiftTests = [
        ("testCompletion", testCompletion),
        ("testEditing", testEditing),
        ("testXMLToMarkdownComment", testXMLToMarkdownComment),
        ("testXMLToMarkdownDeclaration", testXMLToMarkdownDeclaration),
    ]
}

extension SKTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SKTests = [
        ("testInitJSON", testInitJSON),
        ("testInitLocal", testInitLocal),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SKLocalSwiftTests.__allTests__SKLocalSwiftTests),
        testCase(SKTests.__allTests__SKTests),
    ]
}
#endif
