#if !canImport(ObjectiveC)
import XCTest

extension SupportTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SupportTests = [
        ("testFindSubsequence", testFindSubsequence),
        ("testIntFromAscii", testIntFromAscii),
        ("testLineTable", testLineTable),
        ("testLineTableAppendPerf", testLineTableAppendPerf),
        ("testLineTableEditing", testLineTableEditing),
        ("testLineTableLinePositionTranslation", testLineTableLinePositionTranslation),
        ("testLineTableSingleCharEditPerf", testLineTableSingleCharEditPerf),
        ("testLogging", testLogging),
        ("testResultEquality", testResultEquality),
        ("testResultProjection", testResultProjection),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SupportTests.__allTests__SupportTests),
    ]
}
#endif
