#if !canImport(ObjectiveC)
import XCTest

extension SwiftPMWorkspaceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftPMWorkspaceTests = [
        ("testBasicCXXArgs", testBasicCXXArgs),
        ("testBasicSwiftArgs", testBasicSwiftArgs),
        ("testMultiFileSwift", testMultiFileSwift),
        ("testMultiTargetSwift", testMultiTargetSwift),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftPMWorkspaceTests.__allTests__SwiftPMWorkspaceTests),
    ]
}
#endif
