#if !canImport(ObjectiveC)
import XCTest

extension CompilationDatabaseTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CompilationDatabaseTests = [
        ("testCompilationDatabaseBuildSystem", testCompilationDatabaseBuildSystem),
        ("testDecodeCompDBCommand", testDecodeCompDBCommand),
        ("testEncodeCompDBCommand", testEncodeCompDBCommand),
        ("testJSONCompilationDatabaseCoding", testJSONCompilationDatabaseCoding),
        ("testJSONCompilationDatabaseFromDirectory", testJSONCompilationDatabaseFromDirectory),
        ("testJSONCompilationDatabaseLookup", testJSONCompilationDatabaseLookup),
        ("testSplitShellEscapedCommand", testSplitShellEscapedCommand),
    ]
}

extension ToolchainRegistryTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ToolchainRegistryTests = [
        ("testDefaultBasic", testDefaultBasic),
        ("testDefaultDarwin", testDefaultDarwin),
        ("testDylibNames", testDylibNames),
        ("testFromDirectory", testFromDirectory),
        ("testSearchDarwin", testSearchDarwin),
        ("testSearchExplicitEnv", testSearchExplicitEnv),
        ("testSearchPATH", testSearchPATH),
        ("testSubDirs", testSubDirs),
        ("testUnknownPlatform", testUnknownPlatform),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CompilationDatabaseTests.__allTests__CompilationDatabaseTests),
        testCase(ToolchainRegistryTests.__allTests__ToolchainRegistryTests),
    ]
}
#endif
