#if !canImport(ObjectiveC)
import XCTest

extension CodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingTests = [
        ("testCallHierarchyIncomingCallRanges", testCallHierarchyIncomingCallRanges),
        ("testCustomCodableOptional", testCustomCodableOptional),
        ("testPositionRange", testPositionRange),
        ("testPositionRangeArray", testPositionRangeArray),
        ("testValueCoding", testValueCoding),
        ("testValueOrBool", testValueOrBool),
    ]
}

extension ConnectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConnectionTests = [
        ("testEcho", testEcho),
        ("testEchoError", testEchoError),
        ("testEchoNote", testEchoNote),
    ]
}

extension LanguageServerProtocolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LanguageServerProtocolTests = [
        ("testFileChangeTypeEncoding", testFileChangeTypeEncoding),
        ("testLanguageXFlag", testLanguageXFlag),
        ("testURLEscaping", testURLEscaping),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodingTests.__allTests__CodingTests),
        testCase(ConnectionTests.__allTests__ConnectionTests),
        testCase(LanguageServerProtocolTests.__allTests__LanguageServerProtocolTests),
    ]
}
#endif
